name: Action di Di Ceglie
on: 
    push:
jobs:
    ciao:
        runs-on: ubuntu-latest
        steps:
            - run: python --version
            - run: pip -V
            - run: ls -la
            - run: pwd
            - run: env
            - uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    diceglie
            - run: ls -la
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12.8'

            - run: python --version
            - run: pip install -r diceglie/requirements.txt
            - run: python diceglie/modello-devops.py